#!/usr/bin/env python

'''
    The nesi executable can analyze a .nes rom image for information. In
    particular, nesi will extract the following:

        1. ROM Header (16 bytes)
        2. Mapper information
        3. PRG, CHR size info
        4. Example ROMs similar to this one (useful for emulator testing)
        5. Battery, Mirroring, VRAM, and Trainer information
        6. If bytes 7-15 appear valid or not
'''

from __future__ import print_function

import argparse


def main():
    '''
        The main entry point for nesi. The entry point should parse command
        line arguments and delegate all work to the nesi module.
    '''

    parser = argparse.ArgumentParser(
        description='Specify a .nes rom image to be analyzed'
    )

    parser.add_argument(
        '-r',
        '--rom',
        help='path to a .nes rom image to be analyzed',
        type=str
    )

    args = parser.parse_args()

    if args.rom:
        print('Was given {rom}'.format(rom=args.rom))
    else:
        parser.print_help()


if __name__ == '__main__':
    main()

# vim: ai tabstop=4 expandtab shiftwidth=4 softtabstop=4 ft=python
